name: Build, Scan and Push (Local Registry)

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          # On taggue avec 'latest' pour que ça matche avec le deployment.yaml
          docker build -t localhost:5000/flask-app:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'localhost:5000/flask-app:latest'
          format: 'table'
          exit-code: '0' 
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push image to Local Registry
        run: |
          # L'image est maintenant poussée sur le registre
          docker push localhost:5000/flask-app:latest